platform: Any CPU
configuration: Release

pull_requests:
  do_not_increment_build_number: true

install:
  - cinst gitversion.portable -pre -y
  - cinst gitlink -Pre -y
  - cinst android-sdk
  - ps: Build\install-android-sdk.ps1

before_build:
  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - NuGet restore Source/OxyPlot.AppVeyor.sln
  - gitversion /l console /output buildserver /updateAssemblyInfo

build:
  project: Source/OxyPlot.AppVeyor.sln
  verbosity: minimal
  
after_build:
  - gitlink c:\projects\oxyplot-xamarin -u https://github.com/oxyplot/oxyplot-xamarin -f Source/OxyPlot.AppVeyor.sln -ignore OxyPlot.Windows10,OxyPlot.MonoTouch,OxyPlot.Xamarin.Android,OxyPlot.Xamarin.iOS,OxyPlot.Xamarin.Forms.Platform.Android,OxyPlot.Xamarin.Forms.Platform.iOS,OxyPlot.Xamarin.Forms.Platform.iOS.Classic
  - NuGet pack Source\OxyPlot.Xamarin.Android\OxyPlot.Xamarin.Android.nuspec -version "%GitVersion_NuGetVersion%"
  - NuGet pack Source\OxyPlot.Xamarin.iOS\OxyPlot.Xamarin.iOS.nuspec -version "%GitVersion_NuGetVersion%"
  - NuGet pack Source\OxyPlot.Xamarin.Forms\OxyPlot.Xamarin.Forms.nuspec -version "%GitVersion_NuGetVersion%"

artifacts:
  - path: Output
    name: OxyPlot-Xamarin-$(GitVersion_SemVer)
    type: zip
  - path: '*.nupkg'

deploy:
  provider: NuGet
  server:                  # remove to push to NuGet.org
  api_key:
    secure: kM3Kse+ivuuE5RVoe6dPdw+aguWx56K2YeXujGa9tMPQTms3lv7QxNpTLFMALYNa
  skip_symbols: false
  symbol_server:           # remove to push symbols to SymbolSource.org
  artifact: /.*\.nupkg/  
